// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Patient_Grievance_and_Complaint_Resolution.Data;

#nullable disable

namespace Patient_Grievance_and_Complaint_Resolution.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622112423_RemovePatientPassword")]
    partial class RemovePatientPassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime?>("Dob")
                        .HasColumnType("datetime")
                        .HasColumnName("dob");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("username");

                    b.HasKey("AdminId");

                    b.HasIndex(new[] { "Username" }, "UQ_ADMIN_username")
                        .IsUnique();

                    b.ToTable("ADMIN", "admin");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("completed_at");

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int")
                        .HasColumnName("grievance_id");

                    b.Property<int>("InvestigatorId")
                        .HasColumnType("int")
                        .HasColumnName("investigator_id");

                    b.HasKey("AssignmentId");

                    b.HasIndex(new[] { "GrievanceId" }, "IX_ASSIGNMENTS_grievance_id");

                    b.HasIndex(new[] { "InvestigatorId" }, "IX_ASSIGNMENTS_investigator_id");

                    b.ToTable("ASSIGNMENTS", "grievance");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.AuditLog", b =>
                {
                    b.Property<long>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("action");

                    b.Property<int?>("ChangedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_admin_id");

                    b.Property<int?>("ChangedByInvestigatorId")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_investigator_id");

                    b.Property<int?>("ChangedByPatientId")
                        .HasColumnType("int")
                        .HasColumnName("changed_by_patient_id");

                    b.Property<string>("ChangedField")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("changed_field");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NewValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("old_value");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasColumnName("record_id");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("table_name");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime")
                        .HasColumnName("valid_to");

                    b.HasKey("AuditId");

                    b.HasIndex(new[] { "ChangedByAdminId" }, "idx_audit_admin")
                        .HasFilter("([changed_by_admin_id] IS NOT NULL)");

                    b.HasIndex(new[] { "ChangedByInvestigatorId" }, "idx_audit_investigator")
                        .HasFilter("([changed_by_investigator_id] IS NOT NULL)");

                    b.HasIndex(new[] { "ChangedByPatientId" }, "idx_audit_patient")
                        .HasFilter("([changed_by_patient_id] IS NOT NULL)");

                    b.HasIndex(new[] { "TableName", "RecordId" }, "idx_audit_resource");

                    b.ToTable("AUDIT_LOG", "audit");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("category_name");

                    b.HasKey("CategoryId");

                    b.HasIndex(new[] { "CategoryName" }, "UQ_CATEGORIES_category_name")
                        .IsUnique();

                    b.ToTable("CATEGORIES", "core");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("complaint_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplaintId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<bool>("ConvertedToGrievance")
                        .HasColumnType("bit")
                        .HasColumnName("converted_to_grievance");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("encounter_id");

                    b.Property<int?>("GrievanceId")
                        .HasColumnType("int")
                        .HasColumnName("grievance_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("ComplaintId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("GrievanceId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_COMPLAINTS_department_id");

                    b.HasIndex(new[] { "PatientId" }, "IX_COMPLAINTS_patient_id");

                    b.HasIndex(new[] { "StatusId" }, "IX_COMPLAINTS_status_id");

                    b.ToTable("COMPLAINTS", "grievance");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("department_email");

                    b.Property<string>("DepartmentHead")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_head");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("department_name");

                    b.HasKey("DepartmentId");

                    b.HasIndex(new[] { "DepartmentEmail" }, "UQ_DEPARTMENTS_department_email")
                        .IsUnique();

                    b.HasIndex(new[] { "DepartmentName" }, "UQ_DEPARTMENTS_department_name")
                        .IsUnique();

                    b.ToTable("DEPARTMENTS", "core");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Encounter", b =>
                {
                    b.Property<int>("EncounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("encounter_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncounterId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<DateTime>("EncounterDate")
                        .HasColumnType("datetime")
                        .HasColumnName("encounter_date");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.HasKey("EncounterId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_ENCOUNTERS_department_id");

                    b.HasIndex(new[] { "PatientId" }, "IX_ENCOUNTERS_patient_id");

                    b.ToTable("ENCOUNTERS", "clinical");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Escalation", b =>
                {
                    b.Property<int>("EscalationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("escalation_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EscalationId"));

                    b.Property<string>("ActionTaken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("action_taken");

                    b.Property<DateTime>("EscalatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("escalated_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("EscalatedFrom")
                        .HasColumnType("int")
                        .HasColumnName("escalated_from");

                    b.Property<int>("EscalatedTo")
                        .HasColumnType("int")
                        .HasColumnName("escalated_to");

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int")
                        .HasColumnName("grievance_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at");

                    b.HasKey("EscalationId");

                    b.HasIndex("EscalatedFrom");

                    b.HasIndex("EscalatedTo");

                    b.HasIndex(new[] { "GrievanceId" }, "IX_ESCALATIONS_grievance_id");

                    b.ToTable("ESCALATIONS", "grievance");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", b =>
                {
                    b.Property<int>("GrievanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("grievance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrievanceId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime")
                        .HasColumnName("due_date");

                    b.Property<int?>("EncounterId")
                        .HasColumnType("int")
                        .HasColumnName("encounter_id");

                    b.Property<string>("GrievanceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("grievance_number");

                    b.Property<int?>("InvestigatorId")
                        .HasColumnType("int")
                        .HasColumnName("investigator_id");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit")
                        .HasColumnName("is_escalated");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<string>("Severity")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("severity");

                    b.Property<int?>("SlaId")
                        .HasColumnType("int")
                        .HasColumnName("sla_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("GrievanceId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("SlaId");

                    b.HasIndex(new[] { "DepartmentId" }, "IX_GRIEVANCES_department_id");

                    b.HasIndex(new[] { "DueDate" }, "IX_GRIEVANCES_due_date");

                    b.HasIndex(new[] { "InvestigatorId" }, "IX_GRIEVANCES_investigator_id");

                    b.HasIndex(new[] { "PatientId" }, "IX_GRIEVANCES_patient_id");

                    b.HasIndex(new[] { "StatusId" }, "IX_GRIEVANCES_status_id");

                    b.HasIndex(new[] { "GrievanceNumber" }, "UQ_GRIEVANCES_grv_number")
                        .IsUnique();

                    b.ToTable("GRIEVANCES", "grievance");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Investigator", b =>
                {
                    b.Property<int>("InvestigatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("investigator_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvestigatorId"));

                    b.Property<int>("CurrentLoad")
                        .HasColumnType("int")
                        .HasColumnName("current_load");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("employee_code");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("full_name");

                    b.Property<byte?>("Rating")
                        .HasColumnType("tinyint")
                        .HasColumnName("rating");

                    b.HasKey("InvestigatorId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex(new[] { "EmployeeCode" }, "UQ_INVESTIGATORS_emp_code")
                        .IsUnique();

                    b.ToTable("INVESTIGATORS", "grievance");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"));

                    b.Property<string>("Address")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("char(1)")
                        .HasColumnName("gender")
                        .IsFixedLength();

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Mrn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mrn");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.HasKey("PatientId");

                    b.HasIndex(new[] { "Email" }, "IX_PATIENTS_email");

                    b.HasIndex(new[] { "Email" }, "UQ_PATIENTS_email")
                        .IsUnique();

                    b.HasIndex(new[] { "Mrn" }, "UQ_PATIENTS_mrn")
                        .IsUnique();

                    b.ToTable("PATIENTS", "core");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.PatientCommunication", b =>
                {
                    b.Property<int>("CommId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comm_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommId"));

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int")
                        .HasColumnName("grievance_id");

                    b.Property<int>("PatientId")
                        .HasColumnType("int")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("sent_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.HasKey("CommId");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "GrievanceId" }, "IX_PATIENT_COMMS_grievance_id");

                    b.HasIndex(new[] { "PatientId" }, "IX_PATIENT_COMMS_patient_id");

                    b.ToTable("PATIENT_COMMUNICATIONS", "comms");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Resolution", b =>
                {
                    b.Property<int>("ResolutionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("resolution_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResolutionId"));

                    b.Property<int?>("ApprovedByAdminId")
                        .HasColumnType("int")
                        .HasColumnName("approved_by_admin_id");

                    b.Property<string>("CorrectiveAction")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("corrective_action");

                    b.Property<int>("GrievanceId")
                        .HasColumnType("int")
                        .HasColumnName("grievance_id");

                    b.Property<int>("InvestigatorId")
                        .HasColumnType("int")
                        .HasColumnName("investigator_id");

                    b.Property<string>("PreventiveAction")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("preventive_action");

                    b.Property<string>("ResolutionSummary")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("resolution_summary");

                    b.Property<DateTime>("ResolvedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("resolved_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RootCause")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("root_cause");

                    b.HasKey("ResolutionId");

                    b.HasIndex("ApprovedByAdminId");

                    b.HasIndex("InvestigatorId");

                    b.HasIndex(new[] { "GrievanceId" }, "UQ_RESOLUTIONS_grv_id")
                        .IsUnique();

                    b.ToTable("RESOLUTIONS", "grievance");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Sla", b =>
                {
                    b.Property<int>("SlaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sla_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlaId"));

                    b.Property<int>("AcknowledgmentTimeHrs")
                        .HasColumnType("int")
                        .HasColumnName("acknowledgment_time_hrs");

                    b.Property<int>("EscalationThresholdHrs")
                        .HasColumnType("int")
                        .HasColumnName("escalation_threshold_hrs");

                    b.Property<int>("InvestigationTimeDays")
                        .HasColumnType("int")
                        .HasColumnName("investigation_time_days");

                    b.Property<int>("ResolutionTimeDays")
                        .HasColumnType("int")
                        .HasColumnName("resolution_time_days");

                    b.Property<string>("SeverityLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("severity_level");

                    b.HasKey("SlaId");

                    b.ToTable("SLA", "core");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("status_name");

                    b.HasKey("StatusId");

                    b.HasIndex(new[] { "StatusName" }, "UQ_STATUS_status_name")
                        .IsUnique();

                    b.ToTable("STATUS", "core");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Assignment", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", "Grievance")
                        .WithMany("Assignments")
                        .HasForeignKey("GrievanceId")
                        .IsRequired()
                        .HasConstraintName("FK_ASSIGNMENTS_grievance_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Investigator", "Investigator")
                        .WithMany("Assignments")
                        .HasForeignKey("InvestigatorId")
                        .IsRequired()
                        .HasConstraintName("FK_ASSIGNMENTS_investigator_id");

                    b.Navigation("Grievance");

                    b.Navigation("Investigator");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.AuditLog", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Admin", "ChangedByAdmin")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedByAdminId")
                        .HasConstraintName("FK_AUDIT_LOG_admin_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Investigator", "ChangedByInvestigator")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedByInvestigatorId")
                        .HasConstraintName("FK_AUDIT_LOG_investigator_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Patient", "ChangedByPatient")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ChangedByPatientId")
                        .HasConstraintName("FK_AUDIT_LOG_patient_id");

                    b.Navigation("ChangedByAdmin");

                    b.Navigation("ChangedByInvestigator");

                    b.Navigation("ChangedByPatient");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Complaint", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Category", "Category")
                        .WithMany("Complaints")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_COMPLAINTS_category_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Department", "Department")
                        .WithMany("Complaints")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_COMPLAINTS_department_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Encounter", "Encounter")
                        .WithMany("Complaints")
                        .HasForeignKey("EncounterId")
                        .HasConstraintName("FK_COMPLAINTS_encounter_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", "Grievance")
                        .WithMany("Complaints")
                        .HasForeignKey("GrievanceId")
                        .HasConstraintName("FK_COMPLAINTS_grievance_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Patient", "Patient")
                        .WithMany("Complaints")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_COMPLAINTS_patient_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Status", "Status")
                        .WithMany("Complaints")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_COMPLAINTS_status_id");

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("Encounter");

                    b.Navigation("Grievance");

                    b.Navigation("Patient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Encounter", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Department", "Department")
                        .WithMany("Encounters")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_ENCOUNTERS_department_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Patient", "Patient")
                        .WithMany("Encounters")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_ENCOUNTERS_patient_id");

                    b.Navigation("Department");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Escalation", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Department", "EscalatedFromNavigation")
                        .WithMany("EscalationEscalatedFromNavigations")
                        .HasForeignKey("EscalatedFrom")
                        .IsRequired()
                        .HasConstraintName("FK_ESCALATIONS_escalated_from");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Department", "EscalatedToNavigation")
                        .WithMany("EscalationEscalatedToNavigations")
                        .HasForeignKey("EscalatedTo")
                        .IsRequired()
                        .HasConstraintName("FK_ESCALATIONS_escalated_to");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", "Grievance")
                        .WithMany("Escalations")
                        .HasForeignKey("GrievanceId")
                        .IsRequired()
                        .HasConstraintName("FK_ESCALATIONS_grievance_id");

                    b.Navigation("EscalatedFromNavigation");

                    b.Navigation("EscalatedToNavigation");

                    b.Navigation("Grievance");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Category", "Category")
                        .WithMany("Grievances")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_GRIEVANCES_category_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Department", "Department")
                        .WithMany("Grievances")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_GRIEVANCES_department_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Encounter", "Encounter")
                        .WithMany("Grievances")
                        .HasForeignKey("EncounterId")
                        .HasConstraintName("FK_GRIEVANCES_encounter_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Investigator", "Investigator")
                        .WithMany("Grievances")
                        .HasForeignKey("InvestigatorId")
                        .HasConstraintName("FK_GRIEVANCES_investigator_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Patient", "Patient")
                        .WithMany("Grievances")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_GRIEVANCES_patient_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Sla", "Sla")
                        .WithMany("Grievances")
                        .HasForeignKey("SlaId")
                        .HasConstraintName("FK_GRIEVANCES_sla_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Status", "Status")
                        .WithMany("Grievances")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_GRIEVANCES_status_id");

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("Encounter");

                    b.Navigation("Investigator");

                    b.Navigation("Patient");

                    b.Navigation("Sla");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Investigator", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Department", "Department")
                        .WithMany("Investigators")
                        .HasForeignKey("DepartmentId")
                        .IsRequired()
                        .HasConstraintName("FK_INVESTIGATORS_department_id");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.PatientCommunication", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", "Grievance")
                        .WithMany("PatientCommunications")
                        .HasForeignKey("GrievanceId")
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_COMMS_grievance_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Patient", "Patient")
                        .WithMany("PatientCommunications")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_COMMS_patient_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Status", "Status")
                        .WithMany("PatientCommunications")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_PATIENT_COMMS_status_id");

                    b.Navigation("Grievance");

                    b.Navigation("Patient");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Resolution", b =>
                {
                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Admin", "ApprovedByAdmin")
                        .WithMany("Resolutions")
                        .HasForeignKey("ApprovedByAdminId")
                        .HasConstraintName("FK_RESOLUTIONS_approved_by_admin_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", "Grievance")
                        .WithOne("Resolution")
                        .HasForeignKey("Patient_Grievance_and_Complaint_Resolution.Models.Resolution", "GrievanceId")
                        .IsRequired()
                        .HasConstraintName("FK_RESOLUTIONS_grievance_id");

                    b.HasOne("Patient_Grievance_and_Complaint_Resolution.Models.Investigator", "Investigator")
                        .WithMany("Resolutions")
                        .HasForeignKey("InvestigatorId")
                        .IsRequired()
                        .HasConstraintName("FK_RESOLUTIONS_investigator_id");

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("Grievance");

                    b.Navigation("Investigator");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Admin", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Resolutions");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Category", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Grievances");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Department", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Encounters");

                    b.Navigation("EscalationEscalatedFromNavigations");

                    b.Navigation("EscalationEscalatedToNavigations");

                    b.Navigation("Grievances");

                    b.Navigation("Investigators");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Encounter", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Grievances");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Grievance", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Complaints");

                    b.Navigation("Escalations");

                    b.Navigation("PatientCommunications");

                    b.Navigation("Resolution");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Investigator", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("AuditLogs");

                    b.Navigation("Grievances");

                    b.Navigation("Resolutions");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Patient", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Complaints");

                    b.Navigation("Encounters");

                    b.Navigation("Grievances");

                    b.Navigation("PatientCommunications");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Sla", b =>
                {
                    b.Navigation("Grievances");
                });

            modelBuilder.Entity("Patient_Grievance_and_Complaint_Resolution.Models.Status", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Grievances");

                    b.Navigation("PatientCommunications");
                });
#pragma warning restore 612, 618
        }
    }
}
